#!/usr/bin/env python3
"""Remove dictionary_oss entries that duplicate mozc4med.tsv entries.

mozc4med.tsv (generated by generate_mozc4med_dictionary.py from the private
mozc4med-dic-csv sources) and mozc/src/data/dictionary_oss/dictionary*.txt
can end up defining the same (reading, word) pair. When that happens the
dictionary_oss copy is redundant -- and can shadow/duplicate the
mozc4med-curated entry -- so this script deletes the matching
dictionary_oss lines.

Comparison key: (reading, word) exact match (POS ids and cost are ignored).
Both files share the same 5-column layout: reading, lid, rid, cost, word.

Usage:
    # Dry-run (default): report what would be removed, change nothing.
    python mozc4med/tool/rm_dictionary_entries.py

    # Actually rewrite dictionary*.txt.
    python mozc4med/tool/rm_dictionary_entries.py --apply

    # Also write the log to a file (e.g. for CI artifact upload).
    python mozc4med/tool/rm_dictionary_entries.py --apply \
        --log-file rm_dictionary_entries.log

    # Override paths (defaults assume a repo-root working directory).
    python mozc4med/tool/rm_dictionary_entries.py \
        --mozc4med src/data/dictionary_manual/mozc4med.tsv \
        --dict-dir src/data/dictionary_oss
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from typing import List, Optional, Set, Tuple

logger = logging.getLogger("rm_dictionary_entries")

DEFAULT_MOZC4MED = os.path.join("src", "data", "dictionary_manual", "mozc4med.tsv")
DEFAULT_DICT_DIR = os.path.join("src", "data", "dictionary_oss")

Pair = Tuple[str, str]


def setup_logging(log_file: Optional[str], verbose: bool) -> None:
  level = logging.DEBUG if verbose else logging.INFO
  logger.setLevel(level)
  logger.handlers.clear()

  fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", "%H:%M:%S")

  console = logging.StreamHandler(sys.stdout)
  console.setFormatter(fmt)
  logger.addHandler(console)

  if log_file:
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setFormatter(fmt)
    logger.addHandler(file_handler)


def load_mozc4med_pairs(path: str) -> Set[Pair]:
  """Loads (reading, word) pairs from mozc4med.tsv.

  Columns: reading, lid, rid, cost, word[, note]. Blank lines and '#'
  comments are ignored.
  """
  pairs: Set[Pair] = set()
  with open(path, encoding="utf-8") as f:
    for lineno, raw in enumerate(f, start=1):
      line = raw.rstrip("\r\n")
      if not line or line.startswith("#"):
        continue
      cols = line.split("\t")
      if len(cols) < 5:
        logger.warning("%s:%d: skipping line with fewer than 5 columns: %r",
                        os.path.basename(path), lineno, line)
        continue
      pairs.add((cols[0], cols[4]))
  logger.info("Loaded %d unique (reading, word) pair(s) from %s", len(pairs), path)
  return pairs


def process_dictionary_file(
    path: str, pairs: Set[Pair], apply: bool
) -> Tuple[int, List[Tuple[int, str]]]:
  """Removes lines matching `pairs` from one dictionary*.txt file.

  Returns (removed_count, [(line_number, line), ...]).
  """
  with open(path, encoding="utf-8") as f:
    lines = f.readlines()

  kept: List[str] = []
  removed: List[Tuple[int, str]] = []

  for lineno, raw in enumerate(lines, start=1):
    line = raw.rstrip("\r\n")
    if not line:
      kept.append(raw)
      continue
    cols = line.split("\t")
    if len(cols) < 5:
      kept.append(raw)
      continue
    if (cols[0], cols[4]) in pairs:
      removed.append((lineno, line))
      logger.debug("%s:%d: removing -> %s", os.path.basename(path), lineno, line)
    else:
      kept.append(raw)

  if removed:
    logger.info("%s: %d line(s) matched for removal", os.path.basename(path), len(removed))
  else:
    logger.debug("%s: no matches", os.path.basename(path))

  if apply and removed:
    tmp_path = path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
      f.writelines(kept)
    os.replace(tmp_path, path)
    logger.info("%s: rewrote file (%d line(s) removed)", os.path.basename(path), len(removed))

  return len(removed), removed


def parse_args(argv: List[str]) -> argparse.Namespace:
  parser = argparse.ArgumentParser(
      description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument("--mozc4med", default=DEFAULT_MOZC4MED,
                       help=f"mozc4med dictionary TSV path (default: {DEFAULT_MOZC4MED})")
  parser.add_argument("--dict-dir", default=DEFAULT_DICT_DIR,
                       help=f"Directory containing dictionary*.txt "
                            f"(default: {DEFAULT_DICT_DIR})")
  parser.add_argument("--apply", action="store_true",
                       help="Rewrite dictionary*.txt files (default: dry-run only)")
  parser.add_argument("--log-file", default=None,
                       help="Optional path to also write the log to")
  parser.add_argument("-v", "--verbose", action="store_true",
                       help="Log each removed line at DEBUG level")
  return parser.parse_args(argv)


def main(argv: List[str]) -> int:
  args = parse_args(argv)
  setup_logging(args.log_file, args.verbose)

  mode = "APPLY" if args.apply else "DRY-RUN"
  logger.info("Mode: %s", mode)
  logger.info("mozc4med: %s", args.mozc4med)
  logger.info("dict-dir: %s", args.dict_dir)

  if not os.path.isfile(args.mozc4med):
    logger.error("mozc4med dictionary file not found: %s", args.mozc4med)
    return 1
  if not os.path.isdir(args.dict_dir):
    logger.error("dict-dir not found: %s", args.dict_dir)
    return 1

  pairs = load_mozc4med_pairs(args.mozc4med)
  if not pairs:
    logger.warning("No valid (reading, word) pairs loaded from mozc4med; nothing to do.")
    return 1

  dict_files = sorted(
      os.path.join(args.dict_dir, name)
      for name in os.listdir(args.dict_dir)
      if name.startswith("dictionary") and name.endswith(".txt")
  )
  if not dict_files:
    logger.error("No dictionary*.txt files found in %s", args.dict_dir)
    return 1
  logger.info("Target files: %s", ", ".join(os.path.basename(p) for p in dict_files))

  total_removed = 0
  matched_pairs: Set[Pair] = set()
  per_file_summary: List[Tuple[str, int]] = []

  for path in dict_files:
    count, removed = process_dictionary_file(path, pairs, apply=args.apply)
    total_removed += count
    per_file_summary.append((os.path.basename(path), count))
    for _, line in removed:
      cols = line.split("\t")
      matched_pairs.add((cols[0], cols[4]))

  logger.info("=== Summary ===")
  for name, count in per_file_summary:
    if count:
      logger.info("  %s: %d line(s)", name, count)
  logger.info("Total removed: %d", total_removed)

  unmatched = pairs - matched_pairs
  logger.info("mozc4med pairs with no match in dictionary*.txt: %d", len(unmatched))
  for reading, word in sorted(unmatched):
    logger.debug("  unmatched: reading=%r word=%r", reading, word)

  if not args.apply:
    logger.info("Dry-run: no files were modified. Pass --apply to rewrite them.")

  return 0


if __name__ == "__main__":
  sys.exit(main(sys.argv[1:]))
